model_list:
  # Modelos locais Ollama
  - model_name: llama3
    litellm_params:
      model: ollama/llama3
      api_base: http://192.168.1.211:11434
  - model_name: mistral
    litellm_params:
      model: ollama/mistral
      api_base: http://192.168.1.211:11434
  - model_name: codellama
    litellm_params:
      model: ollama/codellama
      api_base: http://192.168.1.211:11434

# General Settings
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: "sqlite:///litellm.db"
  
  # Rate Limiting
  max_budget: 1000
  budget_duration: "30d"
  
  # Logging
  enable_logging: true
  log_level: "INFO"
  
  # Caching
  cache:
    type: "redis"
    host: "redis"
    port: 6379
    
  # UI Settings
  ui_username: "admin"
  ui_password: "admin123"  # Change in production!

# Router Settings
router_settings:
  routing_strategy: "least-busy"

# Virtual Keys for User Management
litellm_settings:
  drop_params: true
  set_verbose: false
  json_logs: true
  
  # Success and Error callbacks
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]
  
  # Budget and Rate Limiting
  budget_tracker: "postgres"
  
  # Model Aliases
  model_alias:
    "llama": "llama3" 