model_list:
  # OpenAI Models
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  
  - model_name: gpt-4-turbo
    litellm_params:
      model: openai/gpt-4-turbo
      api_key: os.environ/OPENAI_API_KEY
  
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY

  # Anthropic Models
  - model_name: claude-3-5-sonnet-20241022
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20241022
      api_key: os.environ/ANTHROPIC_API_KEY
  
  - model_name: claude-3-haiku-20240307
    litellm_params:
      model: anthropic/claude-3-haiku-20240307
      api_key: os.environ/ANTHROPIC_API_KEY
  
  - model_name: claude-3-opus-20240229
    litellm_params:
      model: anthropic/claude-3-opus-20240229
      api_key: os.environ/ANTHROPIC_API_KEY

  # Google Models
  - model_name: gemini-1.5-pro
    litellm_params:
      model: google/gemini-1.5-pro
      api_key: os.environ/GOOGLE_API_KEY
  
  - model_name: gemini-1.5-flash
    litellm_params:
      model: google/gemini-1.5-flash
      api_key: os.environ/GOOGLE_API_KEY

  # Groq Models
  - model_name: llama-3.1-70b-versatile
    litellm_params:
      model: groq/llama-3.1-70b-versatile
      api_key: os.environ/GROQ_API_KEY
  
  - model_name: llama-3.1-8b-instant
    litellm_params:
      model: groq/llama-3.1-8b-instant
      api_key: os.environ/GROQ_API_KEY
  
  - model_name: mixtral-8x7b-32768
    litellm_params:
      model: groq/mixtral-8x7b-32768
      api_key: os.environ/GROQ_API_KEY

# General Settings
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: "sqlite:///litellm.db"
  
  # Rate Limiting
  max_budget: 1000
  budget_duration: "30d"
  
  # Logging
  enable_logging: true
  log_level: "INFO"
  
  # Caching
  cache:
    type: "redis"
    host: "redis"
    port: 6379
    
  # UI Settings
  ui_username: "admin"
  ui_password: "admin123"  # Change in production!

# Router Settings
router_settings:
  routing_strategy: "least-busy"
  fallbacks:
    - ["gpt-4o", "gpt-4-turbo", "gpt-3.5-turbo"]
    - ["claude-3-5-sonnet-20241022", "claude-3-haiku-20240307"]
    - ["gemini-1.5-pro", "gemini-1.5-flash"]

# Virtual Keys for User Management
litellm_settings:
  drop_params: true
  set_verbose: false
  json_logs: true
  
  # Success and Error callbacks
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]
  
  # Budget and Rate Limiting
  budget_tracker: "postgres"
  
  # Model Aliases
  model_alias:
    "gpt-4": "gpt-4o"
    "claude": "claude-3-5-sonnet-20241022"
    "gemini": "gemini-1.5-pro"
    "llama": "llama-3.1-70b-versatile" 